name: "HTML to Thermal Printer"
description: "HTML print server for ESC/POS Thermal Printers"
version: "0.7"
slug: "htmltothermal"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - type: addon_config
ports:
  7777/tcp: 7777
ingress: true
ingress_port: 7777
ingress_entry: /index.html